/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    'HelloWorld.vue 60430048 p.m.': typeof import('./components/HelloWorld.vue 6-04-30-048 p.m..vue')['default']
    'p.m.': typeof import('./components/HelloWorld.vue 6-04-30-048 p.m..vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
